# Generated by Django 4.0.4 on 2022-07-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trends',
            name='pub_date',
        ),
    ]
